services:
  - type: web
    name: deine-app
    env: python
    buildCommand: pip install -r jds_web/requirements.txt
    startCommand: cd jds_web && python manage.py collectstatic --noinput && gunicorn jds_web.wsgi:application --preload --workers=2 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT
    disk:
      name: backup-data
      mountPath: /opt/render/project/src/jds_web/media
      sizeGB: 10
