# Generated by Django 4.2.30 on 2026-06-19 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Unternehmen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mein Unternehmen', max_length=255, verbose_name='Firmenname')),
                ('backup_retention_days', models.IntegerField(default=5, verbose_name='Aufbewahrungsdauer (Tage)')),
                ('max_file_size_mb', models.IntegerField(default=500, verbose_name='Max. Dateigröße (MB)')),
                ('notify_on_failure', models.BooleanField(default=True, verbose_name='Bei Fehlern benachrichtigen')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Benachrichtigungs-E-Mail')),
                ('storage_limit_gb', models.IntegerField(default=10, verbose_name='Speicherlimit (GB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unternehmenseinstellung',
                'verbose_name_plural': 'Unternehmenseinstellungen',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backup_app.company', verbose_name='Unternehmen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzer-Profil',
                'verbose_name_plural': 'Nutzer-Profile',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Client-Name')),
                ('machine_id', models.CharField(max_length=255, unique=True, verbose_name='Maschinen-ID')),
                ('api_token', models.CharField(max_length=255, unique=True, verbose_name='API-Token')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Betriebssystem')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gesehen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('max_backups', models.IntegerField(default=30, verbose_name='Max. Backups')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='backup_app.company', verbose_name='Unternehmen')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.IntegerField(default=60, verbose_name='Intervall (Minuten)')),
                ('paths', models.TextField(default='C:\\Users', verbose_name='Zu sichernde Pfade')),
                ('exclude_patterns', models.TextField(blank=True, verbose_name='Ausgeschlossene Muster')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='backup_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Backup-Plan',
                'verbose_name_plural': 'Backup-Pläne',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warnung'), ('error', 'Fehler'), ('debug', 'Debug')], default='info', max_length=20, verbose_name='Level')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backup_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Log-Eintrag',
                'verbose_name_plural': 'Log-Einträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20, verbose_name='Status')),
                ('total_files', models.IntegerField(default=0, verbose_name='Dateien gesamt')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='Größe gesamt (Bytes)')),
                ('transferred_size', models.BigIntegerField(default=0, verbose_name='Übertragen (Bytes)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='backup_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Backup-Job',
                'verbose_name_plural': 'Backup-Jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024, verbose_name='Dateipfad')),
                ('file_name', models.CharField(max_length=512, verbose_name='Dateiname')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße')),
                ('file_hash', models.CharField(max_length=64, verbose_name='SHA-256 Hash')),
                ('storage_path', models.CharField(max_length=1024, verbose_name='Speicherpfad')),
                ('is_directory', models.BooleanField(default=False, verbose_name='Verzeichnis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backup_app.backupjob', verbose_name='Backup-Job')),
            ],
            options={
                'verbose_name': 'Backup-Datei',
                'verbose_name_plural': 'Backup-Dateien',
            },
        ),
    ]
